version: '3'
services:
  portfolio:
    build: './2020-portfolio-site'
    ports:
      - "3000:3000"
    environment:
      - MONGO_DB_URI=mongodb://db/portfolio
    depends_on: 
      - db  

  sushi-web:
    build: './sushi-web'
    ports:
      - "3001:3000"
    environment:
      - API_BASE_URI="140.82.37.137"
      
  sushi-server:
    build: './sushi-service'
    ports:
      - "3002:3000"
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices

  db:
    image: mongo
    ports:
      - "27017:27017"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./sushi-web/public:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - sushi-web
      - sushi-server
      - portfolio


