version: '3'
services:
  web:
    build: './web'
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - API_BASE_URI="140.82.37.137"
      
  sushi:
    build: './sushiService'
    ports:
      - "3002:3000"
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices

  db:
    image: mongo
    ports:
      - "27017:27017"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./web/public:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - sushi


